routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::resource('/', 'PengunjungHomeController');

//Selayang Pandang====================================================
Route::get('site_selayang_pandang', 'PengunjungSelayangPandangController@index');

//Tugas pokok dan fungsi====================================================
Route::get('site_tupoksi', 'PengunjungTupoksiController@index');

//Struktur Organisasi====================================================
Route::get('site_struktur_organisasi', 'PengunjungStrukturOrganisasiController@index');

//Penghargaan====================================================
Route::get('site_penghargaan', 'PengunjungPenghargaanController@index');

//OSS====================================================
Route::get('site_oss', 'PengunjungOssController@index');

//Pemenuhan Komitmen====================================================
Route::get('site_komitmen', 'PengunjungKomitmenController@index');

//Perizinan Online====================================================
Route::get('site_perizinan', 'PengunjungPerizinanController@index');

//Tracking Berkas====================================================
Route::get('site_tracking_berkas', 'PengunjungTrackingBerkasController@index');

//Pencarian KBLI====================================================
Route::get('site_pencarian_kbli', 'PengunjungPencarianKbliController@index');

//Pengaduan====================================================
Route::get('site_pengaduan', 'PengunjungPengaduanController@index');
Route::post('site_pengaduan_post', 'PengunjungPengaduanController@store');

//Regulasi====================================================
Route::get('site_regulasi', 'PengunjungRegulasiController@index');

//Potensi====================================================
Route::get('site_potensi', 'PengunjungPotensiController@index');
Route::get('site_potensi/{id}', 'PengunjungPotensiController@detail');

//Panduan====================================================
Route::get('site_panduan', 'PengunjungPanduanController@index');

//Peraturan====================================================
Route::get('site_peraturan', 'PengunjungPeratuanController@index');

//BERITA====================================================
Route::get('site_berita', 'PengunjungBeritaController@index');
Route::get('site_berita/{id}', 'PengunjungBeritaController@detail');
Route::post('site_berita_cari', 'PengunjungBeritaController@cari');

//Peraturan====================================================
Route::get('site_laporan', 'PengunjungLaporanController@index');

//Galeri====================================================
Route::get('site_galeri', 'PengunjungGaleriController@index');
Route::get('site_galeri/{id}', 'PengunjungGaleriController@detail');

//Inovasi Layanan====================================================
Route::get('site_inovasi_layanan', 'PengunjungInovasiLayananController@index');
Route::get('site_inovasi_layanan/{id}', 'PengunjungInovasiLayananController@detail');

//  ================================================ ADMIN ==========================================================

Route::group(['middleware' => 'auth'], function () {

  Route::get('index_admin.html', 'PecahTemplateAdminController@index');
  Route::resource('admin_user', 'AdminUserController');

  //  ================================================ MASTER USER ==========================================================
    Route::get('data_master_user', 'MasterUserController@listData')->name('data_master_user');
    Route::resource('master_user', 'MasterUserController');
  //  ================================================ END MASTER USER ==========================================================
  //  ================================================ BERITA ==========================================================
    Route::resource('admin_berita', 'AdminBeritaController');
  //  ================================================ END BERITA ==========================================================
  //  ================================================ PANDUAN ==========================================================
    Route::resource('admin_panduan', 'AdminPanduanController');
  //  ================================================ END PANDUAN ==========================================================
  //  ================================================ PERATURAN ==========================================================
    Route::resource('admin_peraturan', 'AdminPeraturanController');
  //  ================================================ END PERATURAN ==========================================================
  //  ================================================ PENGHARGAAN ==========================================================
    Route::resource('admin_penghargaan', 'AdminPenghargaanController');
  //  ================================================ END PENGHARGAAN ==========================================================
  //  ================================================ SLIDESHOW ==========================================================
    Route::resource('admin_slideshow', 'AdminSlideshowController');
  //  ================================================ END SLIDESHOW ==========================================================
  //  ================================================ Popup ==========================================================
    Route::resource('admin_popup', 'AdminPopupController');
    Route::post('admin_popup/update_aktif', 'AdminPopupController@update_checkbox');
  //  ================================================ END Popup ==========================================================
    // Route::get('data_master_biodata_pejabat', 'AdminBiodataPejabatController@listData')->name('data_master_biodata_pejabat');
    Route::resource('master_biodata_pejabat', 'AdminBiodataPejabatController');
  //  ================================================ END Popup ==========================================================
    Route::post('admin_pengaduan/update_aktif', 'AdminPengaduanController@update_checkbox');
    Route::post('admin_pengaduan/balas', 'AdminPengaduanController@balas_pengaduan');
    Route::resource('admin_pengaduan', 'AdminPengaduanController');


  //================================================= Admin Video =========================================================
  Route::get('data_admin_video', 'AdminVideoController@listData')->name('data_admin_video');
  Route::resource('admin_video', 'AdminVideoController');
  //================================================= Admin Video =========================================================

  //  ================================================ POTENSI ==========================================================
    Route::resource('admin_potensi', 'AdminPotensiController');
  //  ================================================ END POTENSI ==========================================================

  //  ================================================ INOVASI LAYANAN ==========================================================
    Route::resource('admin_inovasi_layanan', 'AdminInovasiLayananController');
  //  ================================================ END INOVASI LAYANAN ==========================================================

  //  ================================================ Galeri ==========================================================
    Route::resource('admin_galeri', 'AdminGaleriController');
  //  ================================================ END Galeri ==========================================================

  //  ================================================ END ADMIN ==========================================================

  //  ================================================ SLIDESHOW ==========================================================
    Route::get('admin_panduan_aplikasi', 'AdminPanduanAplikasiController@index');
  //  ================================================ END SLIDESHOW ==========================================================


  //  ================================================ Selayang pandang ==========================================================
    Route::resource('admin_selayang_pandang', 'AdminSelayangPandangController');
  //  ================================================ END Selayang pandang ==========================================================

  //  ================================================ Tupoksi ==========================================================
    Route::resource('admin_tupoksi', 'AdminTupoksiController');
  //  ================================================ END Tupoksi ==========================================================

  //  ================================================ Struktur Organisasi ==========================================================
    Route::resource('admin_struktur_organisasi', 'AdminStrukturOrganisasiController');
  //  ================================================ END Struktur Organisasi ==========================================================



});

resources/views/admin/pengaduan/create.blade.php
<?php $hal = "admin_berita"; ?>
@extends('layouts.admin.master')
@section('title', 'Berita')

@section('css')
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.4/summernote.css" rel="stylesheet">

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Berita
		<!-- <small>Data barang</small> -->
	</h1>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-xs-12">

			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Data Berita</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					@if(session()->has('msg'))
						<div class="alert alert-success">
							{{ session()->get('msg') }}
						</div>
						@endif
						<form role="form" action="{{route('admin_berita.store')}}" method="post" enctype="multipart/form-data">
							{{csrf_field()}}
							{{method_field('post')}}
							<div class="box-body">
								<div class="form-group">
									<label for="exampleInputEmail1">Judul</label>
									<input type="text" class="form-control" name="berita_nama" placeholder="Judul Berita">
								</div>
								<div class="form-group">
									<label for="exampleInputPassword1">Isi</label>
									<textarea class="form-control summernote" name="berita_isi"></textarea>
								</div>
								{{-- <div class="form-group">
               <label for="exampleInputFile">File input</label>
               <input type="file" id="exampleInputFile">

               <p class="help-block">Example block-level help text here.</p>
             </div> --}}
								{{-- <div class="checkbox">
               <label>
                 <input type="checkbox"> Check me out
               </label>
             </div> --}}
							</div>
							<!-- /.box-body -->

							<div class="box-footer">
								<button type="submit" class="btn btn-primary">Simpan</button>
							</div>
						</form>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
		<!-- /.col -->
	</div>
	<!-- /.row -->
</section>
<!-- /.content -->

@endsection

@section('js')
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.4/summernote.js"></script>

<script type="text/javascript">
	$(document).ready(function() {

		$('.summernote').summernote({

			height: 300,

		});

	});
</script>

@endsection

resources/views/admin/pengaduan/edit.blade.php
<?php $hal = "admin_berita"; ?>
@extends('layouts.admin.master')
@section('title', 'Berita')

@section('css')
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.4/summernote.css" rel="stylesheet">

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Berita
		<!-- <small>Data barang</small> -->
	</h1>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-xs-12">

			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Data Berita</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					@if(session()->has('msg'))
						<div class="alert alert-success">
							{{ session()->get('msg') }}
						</div>
						@endif
						<form role="form" action="{{route('admin_berita.update',$berita->berita_id)}}" method="post" enctype="multipart/form-data">
							{{csrf_field()}}
							{{method_field('PUT')}}
							<div class="box-body">
								<div class="form-group">
									<label for="exampleInputEmail1">Judul</label>
									<input type="text" class="form-control" value="{{$berita->berita_nama}}" name="berita_nama" placeholder="Judul Berita">
								</div>
								<div class="form-group">
									<label for="exampleInputPassword1">Isi</label>
									<textarea class="form-control summernote" name="berita_isi">   {!! $berita->berita_isi !!}</textarea>
								</div>
								{{-- <div class="form-group">
               <label for="exampleInputFile">File input</label>
               <input type="file" id="exampleInputFile">

               <p class="help-block">Example block-level help text here.</p>
             </div> --}}
								{{-- <div class="checkbox">
               <label>
                 <input type="checkbox"> Check me out
               </label>
             </div> --}}
							</div>
							<!-- /.box-body -->

							<div class="box-footer">
								<button type="submit" class="btn btn-primary">Simpan</button>
							</div>
						</form>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
		<!-- /.col -->
	</div>
	<!-- /.row -->
</section>
<!-- /.content -->

@endsection

@section('js')
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.4/summernote.js"></script>

<script type="text/javascript">
	$(document).ready(function() {

		$('.summernote').summernote({

			height: 300,

		});

	});
</script>

@endsection

resources/views/admin/pengaduan/index.blade.php
<?php $hal = "admin_pengaduan"; ?>
@extends('layouts.admin.master')
@section('title', 'Pengaduan')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('public/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin/bower_components/select2/dist/css/select2.min.css')}}">

<style>
  .example-modal .modal {
    position: relative;
    top: auto;
    bottom: auto;
    right: auto;
    left: auto;
    display: block;
    z-index: 1;
  }

  .example-modal .modal {
    background: transparent !important;
  }
</style>

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Pengaduan
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Data Pengaduan</h3>
        </div>
        {{-- <a href="{{route('admin_berita.create')}}" style="margin-bottom:20px;margin-left:10px;" class="card-body-title"><button class="btn btn-primary"><i class="fa  fa-plus-square-o"></i> Tambah</button></a> --}}

        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th style="width:2%;">No#</th>
                <th style="width:30%;">Nama</th>
                <th style="width:20%;">Status</th>
                <th style="width:20%;">Non-Aktif</th>
                <th style="width:28;">Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($pengaduan as $data)

              <tr id="{{$data->pengaduan_id}}">
                <td>{{$no++}}</td>
                <td>{{$data->pengaduan_nama}}</td>
                @if ($data->pengaduan_status_balas == 2)
                <td><span class="badge" style="background-color:#fca103">Belum Ada Tanggapan</span></td>
              @else
                <td> <span class="badge" style="background-color:green">Sudah di Tanggapi</span></td>

              @endif
                <td> <input type="checkbox" name="pengaduan_aktif" id="pengaduan_aktif"
                  @if ($data->pengaduan_aktif == '2')
                    checked
                  @endif
                  value="2"> </td>
                <td>
                  <form action="{{route('admin_pengaduan.destroy',$data->pengaduan_id)}}" method="post">
                    <a href="{{route('admin_pengaduan.show',$data->pengaduan_id)}}" class="btn btn-success" data-toggle="tooltip" data-placement="botttom" title="Detail Data" style="color:white;"><i class="fa  fa-eye"></i></a>
                    @if ($data->pengaduan_status_balas == 2)
                    <button type="button" name="button" data-toggle="modal" data-id="{{$data->pengaduan_id}}" class="btn btn-primary open-form-balas"  data-placement="botttom" title="Balas Pengaduan" style="color:white;"><i class="fa  fa-edit"></i></button>
                    @else
                    <button type="button" disabled name="button" data-toggle="modal" data-id="{{$data->pengaduan_id}}" class="btn btn-primary open-form-balas"  data-placement="botttom" title="Balas Pengaduan" style="color:white;"><i class="fa  fa-edit"></i></button>
                    @endif
                    {{-- <a href="{{route('admin_berita.edit',$data->berita_id)}}" class="btn btn-primary" data-toggle="tooltip" data-placement="botttom" title="Balas Pengaduan" style="color:white;"><i class="fa  fa-edit"></i></a> --}}
                    {{csrf_field()}}
                    {{method_field("DELETE")}}
                    <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="botttom" title="Hapus Data" style="color:white;"><i class="fa  fa-trash"> </i></button>
                  </form>
                </td>
              </tr>
              @endforeach
              </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->
<!-- Modal -->
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Kirim balasan atas pengaduan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="" action="{{url('admin_pengaduan/balas')}}" method="post">
          {{csrf_field()}} {{method_field("POST")}}
          <input type="hidden" name="id_pengaduan" id="id_pengaduan" value="">
          <label for="pengaduan_balas">Pesan</label>
          <textarea name="pengaduan_balas" class="form-control" rows="8" cols="80"></textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
        <button type="submit" class="btn btn-primary">Kirim</button>
      </div>
    </form>
    </div>
  </div>
</div>
@endsection


@section('js')
<!-- DataTables -->
<script src="{{asset('public/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('public/admin/bower_components/select2/dist/js/select2.full.min.js')}}"></script>



<script>
// Open Modal With ID
$(document).on("click", ".open-form-balas", function () {
     var id_pengaduan = $(this).data('id');
     $(".modal-body #id_pengaduan").val( id_pengaduan );
    $('#modal-form').modal('show');
});

$(document).ready(function(){
  $("input:checkbox").change(function() {
    var pengaduan_id = $(this).closest('tr').attr('id');
    // console.log(program_id);
    $.ajax({
            type:'POST',
            url:'admin_pengaduan/update_aktif',
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}' },
            data: { "id" : pengaduan_id },
            success: function(data){
              if(data.data.success){
                // console.log(data);
              }
            }
        });
    });
});

  $(function() {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging': true,
      'lengthChange': false,
      'searching': false,
      'ordering': true,
      'info': true,
      'autoWidth': false
    })
  })
</script>



@endsection

resources/views/admin/pengaduan/show.blade.php
<?php $hal = "admin_pengaduan"; ?>
@extends('layouts.admin.master')
@section('title', 'Berita')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('public/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin/bower_components/select2/dist/css/select2.min.css')}}">

<style>
    .example-modal .modal {
      position: relative;
      top: auto;
      bottom: auto;
      right: auto;
      left: auto;
      display: block;
      z-index: 1;
    }

    .example-modal .modal {
      background: transparent !important;
    }
    .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 30%;
}
  </style>

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Pengaduan
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Detail </h3>
        </div>
        <a href="{{route('admin_pengaduan.index')}}" class="btn btn-primary" style=" margin-left: 20px;color:white;"> <i class="fa fa-arrow-left"></i> </a>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-lg-5">
              <div class="box">
                <h2>Profile</h2>
                <div class="col-md-12">
                  <div class="col-md-6">
                      <label for="">Nama</label>
                  </div>
                  <div class="col-md-6">
                      <p>{{$pengaduan->pengaduan_nama}}</p>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="col-md-6">
                      <label for="">Email</label>
                  </div>
                  <div class="col-md-6">
                      <p>{{$pengaduan->pengaduan_email}}</p>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="col-md-6">
                      <label for="">No Telp</label>
                  </div>
                  <div class="col-md-6">
                      <p>{{$pengaduan->pengaduan_telp}}</p>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="col-md-6">
                      <label for="">Alamat</label>
                  </div>
                  <div class="col-md-6">
                      <p>{{$pengaduan->pengaduan_alamat}}</p>
                  </div>
                </div>

              </div>
            </div>
            <div class="col-lg-7">
              <div class="box">
                <h2>Pengaduan</h2>
                <div class="col-md-12">
                  <p>{{$pengaduan->pengaduan_data}}</p>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->

@endsection