routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::resource('/', 'PengunjungHomeController');

//Selayang Pandang====================================================
Route::get('site_selayang_pandang', 'PengunjungSelayangPandangController@index');

//Tugas pokok dan fungsi====================================================
Route::get('site_tupoksi', 'PengunjungTupoksiController@index');

//Struktur Organisasi====================================================
Route::get('site_struktur_organisasi', 'PengunjungStrukturOrganisasiController@index');

//Penghargaan====================================================
Route::get('site_penghargaan', 'PengunjungPenghargaanController@index');

//OSS====================================================
Route::get('site_oss', 'PengunjungOssController@index');

//Pemenuhan Komitmen====================================================
Route::get('site_komitmen', 'PengunjungKomitmenController@index');

//Perizinan Online====================================================
Route::get('site_perizinan', 'PengunjungPerizinanController@index');

//Tracking Berkas====================================================
Route::get('site_tracking_berkas', 'PengunjungTrackingBerkasController@index');

//Pencarian KBLI====================================================
Route::get('site_pencarian_kbli', 'PengunjungPencarianKbliController@index');

//Pengaduan====================================================
Route::get('site_pengaduan', 'PengunjungPengaduanController@index');
Route::post('site_pengaduan_post', 'PengunjungPengaduanController@store');

//Regulasi====================================================
Route::get('site_regulasi', 'PengunjungRegulasiController@index');

//Potensi====================================================
Route::get('site_potensi', 'PengunjungPotensiController@index');
Route::get('site_potensi/{id}', 'PengunjungPotensiController@detail');

//Panduan====================================================
Route::get('site_panduan', 'PengunjungPanduanController@index');

//Peraturan====================================================
Route::get('site_peraturan', 'PengunjungPeratuanController@index');

//BERITA====================================================
Route::get('site_berita', 'PengunjungBeritaController@index');
Route::get('site_berita/{id}', 'PengunjungBeritaController@detail');
Route::post('site_berita_cari', 'PengunjungBeritaController@cari');

//Peraturan====================================================
Route::get('site_laporan', 'PengunjungLaporanController@index');

//Galeri====================================================
Route::get('site_galeri', 'PengunjungGaleriController@index');
Route::get('site_galeri/{id}', 'PengunjungGaleriController@detail');

//Inovasi Layanan====================================================
Route::get('site_inovasi_layanan', 'PengunjungInovasiLayananController@index');
Route::get('site_inovasi_layanan/{id}', 'PengunjungInovasiLayananController@detail');

//  ================================================ ADMIN ==========================================================

Route::group(['middleware' => 'auth'], function () {

  Route::get('index_admin.html', 'PecahTemplateAdminController@index');
  Route::resource('admin_user', 'AdminUserController');

  //  ================================================ MASTER USER ==========================================================
    Route::get('data_master_user', 'MasterUserController@listData')->name('data_master_user');
    Route::resource('master_user', 'MasterUserController');
  //  ================================================ END MASTER USER ==========================================================
  //  ================================================ BERITA ==========================================================
    Route::resource('admin_berita', 'AdminBeritaController');
  //  ================================================ END BERITA ==========================================================
  //  ================================================ PANDUAN ==========================================================
    Route::resource('admin_panduan', 'AdminPanduanController');
  //  ================================================ END PANDUAN ==========================================================
  //  ================================================ PERATURAN ==========================================================
    Route::resource('admin_peraturan', 'AdminPeraturanController');
  //  ================================================ END PERATURAN ==========================================================
  //  ================================================ PENGHARGAAN ==========================================================
    Route::resource('admin_penghargaan', 'AdminPenghargaanController');
  //  ================================================ END PENGHARGAAN ==========================================================
  //  ================================================ SLIDESHOW ==========================================================
    Route::resource('admin_slideshow', 'AdminSlideshowController');
  //  ================================================ END SLIDESHOW ==========================================================
  //  ================================================ Popup ==========================================================
    Route::resource('admin_popup', 'AdminPopupController');
    Route::post('admin_popup/update_aktif', 'AdminPopupController@update_checkbox');
  //  ================================================ END Popup ==========================================================
    // Route::get('data_master_biodata_pejabat', 'AdminBiodataPejabatController@listData')->name('data_master_biodata_pejabat');
    Route::resource('master_biodata_pejabat', 'AdminBiodataPejabatController');
  //  ================================================ END Popup ==========================================================
    Route::post('admin_pengaduan/update_aktif', 'AdminPengaduanController@update_checkbox');
    Route::post('admin_pengaduan/balas', 'AdminPengaduanController@balas_pengaduan');
    Route::resource('admin_pengaduan', 'AdminPengaduanController');


  //================================================= Admin Video =========================================================
  Route::get('data_admin_video', 'AdminVideoController@listData')->name('data_admin_video');
  Route::resource('admin_video', 'AdminVideoController');
  //================================================= Admin Video =========================================================

  //  ================================================ POTENSI ==========================================================
    Route::resource('admin_potensi', 'AdminPotensiController');
  //  ================================================ END POTENSI ==========================================================

  //  ================================================ INOVASI LAYANAN ==========================================================
    Route::resource('admin_inovasi_layanan', 'AdminInovasiLayananController');
  //  ================================================ END INOVASI LAYANAN ==========================================================

  //  ================================================ Galeri ==========================================================
    Route::resource('admin_galeri', 'AdminGaleriController');
  //  ================================================ END Galeri ==========================================================

  //  ================================================ END ADMIN ==========================================================

  //  ================================================ SLIDESHOW ==========================================================
    Route::get('admin_panduan_aplikasi', 'AdminPanduanAplikasiController@index');
  //  ================================================ END SLIDESHOW ==========================================================


  //  ================================================ Selayang pandang ==========================================================
    Route::resource('admin_selayang_pandang', 'AdminSelayangPandangController');
  //  ================================================ END Selayang pandang ==========================================================

  //  ================================================ Tupoksi ==========================================================
    Route::resource('admin_tupoksi', 'AdminTupoksiController');
  //  ================================================ END Tupoksi ==========================================================

  //  ================================================ Struktur Organisasi ==========================================================
    Route::resource('admin_struktur_organisasi', 'AdminStrukturOrganisasiController');
  //  ================================================ END Struktur Organisasi ==========================================================



});

resources/views/admin/potensi/create.blade.php
<?php $hal = "admin_potensi"; ?>
@extends('layouts.admin.master')
@section('title', 'Potensi')

@section('css')
<link rel="stylesheet" href="{{ asset('public/admin/dist/css/summernote.css') }}">

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Potensi
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">

      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Data Potensi</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          @if(session()->has('msg'))
          <div class="alert alert-success">
            {{ session()->get('msg') }}
          </div>
          @endif
          <form role="form" action="{{route('admin_potensi.store')}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            {{method_field('post')}}
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Nama Potensi</label>
                <input type="text" class="form-control" name="potensi_nama" placeholder="Judul Potensi">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Isi</label>
                <textarea class="form-control summernote" name="potensi_isi"></textarea>
              </div>
              {{-- <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" id="exampleInputFile">

                <p class="help-block">Example block-level help text here.</p>
              </div> --}}
              {{-- <div class="checkbox">
                <label>
                  <input type="checkbox"> Check me out
                </label>
              </div> --}}
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
          </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->

@endsection

@section('js')
<script src="{{ asset('public/admin/dist/js/summernote.js')}}"></script>

<script type="text/javascript">
$(document).ready(function() {

  $('.summernote').summernote({

    height: 300,

  });

});
</script>

@endsection

resources/views/admin/potensi/edit.blade.php
<?php $hal = "admin_potensi"; ?>
@extends('layouts.admin.master')
@section('title', 'Potensi')

@section('css')
<link rel="stylesheet" href="{{ asset('public/admin/dist/css/summernote.css') }}">

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Potensi
		<!-- <small>Data barang</small> -->
	</h1>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-xs-12">

			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Edit Data Potensi</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					@if(session()->has('msg'))
						<div class="alert alert-success">
							{{ session()->get('msg') }}
						</div>
						@endif
						<form role="form" action="{{route('admin_potensi.update',$potensi->potensi_id)}}" method="post" enctype="multipart/form-data">
							{{csrf_field()}}
							{{method_field('PUT')}}
							<div class="box-body">
								<div class="form-group">
									<label for="exampleInputEmail1">Nama Potensi</label>
									<input type="text" class="form-control" value="{{$potensi->potensi_nama}}" name="potensi_nama" placeholder="Judul Berita">
								</div>
								<div class="form-group">
									<label for="exampleInputPassword1">Isi</label>
									<textarea class="form-control summernote" name="potensi_isi">   {!! $potensi->potensi_isi !!}</textarea>
								</div>
								{{-- <div class="form-group">
               <label for="exampleInputFile">File input</label>
               <input type="file" id="exampleInputFile">

               <p class="help-block">Example block-level help text here.</p>
             </div> --}}
								{{-- <div class="checkbox">
               <label>
                 <input type="checkbox"> Check me out
               </label>
             </div> --}}
							</div>
							<!-- /.box-body -->

							<div class="box-footer">
								<button type="submit" class="btn btn-primary">Simpan</button>
							</div>
						</form>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
		<!-- /.col -->
	</div>
	<!-- /.row -->
</section>
<!-- /.content -->

@endsection

@section('js')
<script src="{{ asset('public/admin/dist/js/summernote.js')}}"></script>

<script type="text/javascript">
	$(document).ready(function() {

		$('.summernote').summernote({

			height: 300,

		});

	});
</script>

@endsection

resources/views/admin/potensi/index.blade.php
<?php $hal = "admin_potensi"; ?>
@extends('layouts.admin.master')
@section('title', 'Potensi')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('public/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin/bower_components/select2/dist/css/select2.min.css')}}">

<style>
    .example-modal .modal {
      position: relative;
      top: auto;
      bottom: auto;
      right: auto;
      left: auto;
      display: block;
      z-index: 1;
    }

    .example-modal .modal {
      background: transparent !important;
    }
  </style>

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Potensi
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Data Potensi</h3>
        </div>
        <a href="{{route('admin_potensi.create')}}"  style="margin-bottom:20px;margin-left:10px;" class="card-body-title"><button class="btn btn-primary"><i class="fa  fa-plus-square-o"></i> Tambah</button></a>

        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th style="width:2%;">No#</th>
              <th style="width:70%;">Nama Potensi</th>
              <th style="width:28;">Action</th>
            </tr>
            </thead>
            <tbody>
              @foreach ($potensi as $data)
            <tr>
              <td>{{$no++}}</td>
              <td>@php echo (strlen($data->potensi_nama) > 30 ? substr($data->potensi_nama,0,100)." ..." : $data->potensi_nama) @endphp</td>
              {{-- <td>{{$data->potensi_nama}}</td> --}}
              <td>
                <form  action="{{route('admin_potensi.destroy',$data->potensi_id)}}" method="post">
                <a href="{{route('admin_potensi.show',$data->potensi_id)}}" class="btn btn-success" data-toggle="tooltip" data-placement="botttom" title="Detail Data"  style="color:white;"><i class="fa  fa-eye"></i></a>
                 <a href="{{route('admin_potensi.edit',$data->potensi_id)}}" class="btn btn-primary" data-toggle="tooltip" data-placement="botttom" title="Edit Data"  style="color:white;"><i class="fa  fa-edit"></i></a>
                   {{csrf_field()}}
                   {{method_field("DELETE")}}
                   <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-danger" data-toggle="tooltip" data-placement="botttom" title="Hapus Data" style="color:white;"><i class="fa  fa-trash"> </i></button>
                   {{-- <a  onclick='return confirm('Are you sure?')' class="btn btn-danger" data-toggle="tooltip" data-placement="botttom" title="Hapus Data" style="color:white;"><i class="fa  fa-trash"> </i></a> --}}
                 </form>
                 </td>
            </tr>
          @endforeach
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->

@endsection


@section('js')
<!-- DataTables -->
<script src="{{asset('public/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('public/admin/bower_components/select2/dist/js/select2.full.min.js')}}"></script>



<script>
$(function () {
  $('#example1').DataTable()
  $('#example2').DataTable({
    'paging'      : true,
    'lengthChange': false,
    'searching'   : false,
    'ordering'    : true,
    'info'        : true,
    'autoWidth'   : false
  })
})
</script>



@endsection

resources/views/admin/potensi/show.blade.php
<?php $hal = "admin_potensi"; ?>
@extends('layouts.admin.master')
@section('title', 'Potensi')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('public/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin/bower_components/select2/dist/css/select2.min.css')}}">

<style>
    .example-modal .modal {
      position: relative;
      top: auto;
      bottom: auto;
      right: auto;
      left: auto;
      display: block;
      z-index: 1;
    }

    .example-modal .modal {
      background: transparent !important;
    }
    .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 30%;
}
  </style>

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Potensi
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Detail Data Potensi</h3>
        </div>
        <a href="{{route('admin_potensi.index')}}" class="btn btn-primary" style=" margin-left: 20px;color:white;"> <i class="fa fa-arrow-left"></i> </a>
        <!-- /.box-header -->
        <div class="box-body">
          <h2 style="text-align:center;">{{$potensi->potensi_nama}}</h2>
          <img class="center" src="{{asset('public/pengunjung/images/potensi/'.$potensi->potensi_gambar)}}" alt="{{$potensi->potensi_gambar}}">

          {!! $potensi->potensi_isi !!}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->

@endsection